version: '3'

dotenv:
  - '.stage.env'

tasks:
  default: task --list

  dc-local-up:
    desc: Start the local Docker-Compose stack
    cmds:
      - docker-compose up -d
  dc-local-down:
    desc: Stop the local Docker-Compose stack
    cmds:
      - docker-compose down

  stage-tunnel:
    desc: TODO - Open an SSH tunnel to Stage MySQL
    cmds:
      - ssh -o StrictHostKeyChecking=no -L 3306:${STAGE_DB_HOST}:3306 ${SSH_USER}@${SSH_HOST}
    interactive: true
  dc-stage-up:
    desc: Start the Docker-Compose stack to connect to Stage
    cmds:
      - docker-compose -f docker-compose.stage.yaml up -d
  dc-stage-down:
    desc: Stop the Docker-Compose stack connected to Stage
    cmds:
      - docker-compose -f docker-compose.stage.yaml down
