version: '3'

includes:
  dc: ./taskfiles/Taskfile.compose.yml
  k8s: ./taskfiles/Taskfile.k8s.yml

tasks:
  default: task --list

  test-kafka-query:
    internal: true
    cmds:
      - |
        docker run -it --rm \
          --network=kafka-demo-test \
          -v "$PWD/bin/02-db-host-change:/scripts" \
          --entrypoint /scripts/query-kafka \
          confluentinc/cp-kafkacat:latest >> tmp/02-db-host-change
  test-tail-topic:
    internal: true
    cmds:
      - |
        docker run -it --rm \
          --network=kafka-demo-test \
          -v "$PWD/bin/02-db-host-change:/scripts" \
          --entrypoint /scripts/tail-topic \
          confluentinc/cp-kafkacat:latest >> tmp/02-db-host-change
  test-update-connector:
    internal: true
    env:
      CONNECTOR_NAME: source-debezium-00
      MYSQL_HOSTNAME: mysql-new
      MYSQL_PASSWORD: 'dbz'
      MYSQL_SERVER_ID: 1001
    cmds:
      - |
        docker run -it --rm \
          --network=kafka-demo-test \
          -e MYSQL_HOSTNAME -e MYSQL_PASSWORD -e MYSQL_SERVER_ID -e CONNECTOR_NAME \
          -v "$PWD/bin/02-db-host-change:/scripts" \
          --entrypoint /bin/sh \
          curlimages/curl:latest /scripts/update-connector >> tmp/02-db-host-change
  test-db-host-change:
    desc: Test changing the db host for a connector
    deps:
      - dc:test-up
    cmds:
      - echo "Waiting for topics to be ready" && sleep 60
      - task: test-kafka-query
      - task: test-tail-topic
      - echo -e "\n# END INITIAL\n" >> tmp/02-db-host-change
      - docker compose -f docker-compose.test.yaml stop mysql-old
      - sleep 60
      - task: test-kafka-query
      - task: test-tail-topic
      - task: test-update-connector
      - echo -e "\n# END UPDATE\n" >> tmp/02-db-host-change && sleep 60
      - task: test-kafka-query
      - task: test-tail-topic
