apiVersion: v1
kind: Service
metadata:
  labels:
    app: controlcenter
  name: controlcenter
spec:
  ports:
  - name: http
    nodePort: 30950
    port: 9021
    protocol: TCP
    targetPort: http
  selector:
    app: controlcenter
  type: NodePort
