apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeploy
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  strategy: {}
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - image: foo.bar
        name: foo-bar-v76cb
        resources: {}
