apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-svc
  name: my-svc
spec:
  ports:
  - name: http
    nodePort: 30950
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-svc
  type: NodePort
