apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # ingress
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # control-center
      - containerPort: 30950
        hostPort: 9000
        protocol: TCP
