apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  ports:
  - name: broker
    port: 29092
    protocol: TCP
    targetPort: internal
  - name: metrics
    port: 9101
    protocol: TCP
    targetPort: metrics
  selector:
    app: kafka-broker
