apiVersion: v1
kind: ConfigMap
metadata:
  name: curl-execution-cm
data:
  curl-PUT.sh: |
    #!/usr/bin/env sh

    cat <<EOF | curl -v -X PUT --fail-with-body --json @- http://connect-svc.default.svc.cluster.local:8083/connectors/source-debezium-orders-00/config
    {
      "connector.class": "io.debezium.connector.mysql.MySqlConnector",
      "database.hostname": "mysql",
      "database.port": "3306",
      "database.user": "debezium",
      "database.password": "$MY_SQL_PASSWORD",
      "database.server.id": "42",
      "database.server.name": "asgard",
      "table.include.list": "demo.orders",
      "topic.prefix": "asgard",
      "database.history.kafka.bootstrap.servers": "kafka:29092",
      "database.history.kafka.topic": "dbhistory.demo",
      "decimal.handling.mode": "double",
      "include.schema.changes": "true",
      "transforms": "unwrap",
      "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState"
    }
    EOF
