apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
  - name: http
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
